/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinalgrupo45.vistas;

import java.awt.Color;
import proyectofinalgrupo45.entidades.Libros;

/**
 *
 * @author Sorondo
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jRadioButton1 = new javax.swing.JRadioButton();
        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMLibro = new javax.swing.JMenu();
        jMformlibro = new javax.swing.JMenuItem();
        jMejemplar = new javax.swing.JMenu();
        jMformejemplar = new javax.swing.JMenuItem();
        jMprestamo = new javax.swing.JMenu();
        jMformprestamo = new javax.swing.JMenuItem();
        jMformlector = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMsalir = new javax.swing.JMenu();
        jMformsalir = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        escritorio.setMaximumSize(new java.awt.Dimension(2047483647, 2147483647));
        escritorio.setPreferredSize(new java.awt.Dimension(446, 331));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 446, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 336, Short.MAX_VALUE)
        );

        jMLibro.setText("Libro ");
        jMLibro.setMaximumSize(new java.awt.Dimension(41, 32767));

        jMformlibro.setText("Formulario de Libro");
        jMformlibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMformlibroActionPerformed(evt);
            }
        });
        jMLibro.add(jMformlibro);

        jMenuBar1.add(jMLibro);

        jMejemplar.setText("Ejemplar");

        jMformejemplar.setText("Formulario de ejemplar ");
        jMformejemplar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMformejemplarActionPerformed(evt);
            }
        });
        jMejemplar.add(jMformejemplar);

        jMenuBar1.add(jMejemplar);

        jMprestamo.setText("Prestamo");

        jMformprestamo.setText("Formulario de Prestamo");
        jMformprestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMformprestamoActionPerformed(evt);
            }
        });
        jMprestamo.add(jMformprestamo);

        jMenuBar1.add(jMprestamo);

        jMformlector.setText("Lector");

        jMenuItem4.setText("Formulario de Lector");
        jMformlector.add(jMenuItem4);

        jMenuBar1.add(jMformlector);

        jMsalir.setText("Salir");
        jMsalir.add(jMformsalir);

        jMenuBar1.add(jMsalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMformejemplarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMformejemplarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMformejemplarActionPerformed

    private void jMformprestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMformprestamoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMformprestamoActionPerformed

    private void jMformlibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMformlibroActionPerformed
       escritorio.removeAll();
        escritorio.repaint();
        LibroView l = new LibroView();
        l.setVisible(true);
        escritorio.add(l);
        l.getContentPane().setBackground(new Color(68, 167, 132));
        escritorio.moveToFront(l);
    }//GEN-LAST:event_jMformlibroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMLibro;
    private javax.swing.JMenu jMejemplar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMformejemplar;
    private javax.swing.JMenu jMformlector;
    private javax.swing.JMenuItem jMformlibro;
    private javax.swing.JMenuItem jMformprestamo;
    private javax.swing.JMenuItem jMformsalir;
    private javax.swing.JMenu jMprestamo;
    private javax.swing.JMenu jMsalir;
    private javax.swing.JRadioButton jRadioButton1;
    // End of variables declaration//GEN-END:variables
}
